feat(ci): integrate vault with dynamoDB

diff --git a/connector/charts/oaebudt-connector/templates/job-vault-init.yaml b/connector/charts/oaebudt-connector/templates/job-vault-init.yaml
--- a/connector/charts/oaebudt-connector/templates/job-vault-init.yaml
+++ b/connector/charts/oaebudt-connector/templates/job-vault-init.yaml
@@ -1,4 +1,3 @@
-{{- if .Release.IsInstall }}
 ---
 apiVersion: batch/v1
 kind: Job
@@ -14,6 +13,9 @@ spec:
       name: {{ .Release.Name }}-vault-init
       labels:
         {{- include "oaebudt-connector.labels" . | nindent 8 }}
+      annotations:
+        "helm.sh/hook": pre-install
+        "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
     spec:
       serviceAccountName: {{ .Release.Name }}-vault-init-sa
       restartPolicy: OnFailure
@@ -28,6 +30,16 @@ spec:
               apt-get update && apt-get install -y curl jq unzip
               curl -o vault.zip https://releases.hashicorp.com/vault/1.19.2/vault_1.19.2_linux_amd64.zip
               unzip vault.zip && mv vault /usr/local/bin/ && chmod +x /usr/local/bin/vault
+
+              echo "Checking if Vault is already initialized..."
+              if curl -s http://{{ .Release.Name }}-vault:8200/v1/sys/health | grep -q '"initialized":true'; then
+                echo "Vault is already initialized. Skipping initialization steps."
+                echo "IMPORTANT: This job is expected to perform the initial Vault setup and create the root token needed by the connector."
+                echo "Since Vault is already initialized, the root token won't be created, and the connector won't be able to authenticate."
+                echo "As a result, the Helm chart release will fail due to missing initialization and bootstrapping of Vault."
+                echo "To reinitialize Vault, you must first clean the backend storage used by Vault)."
+                exit 42
+              fi
 
               echo "Waiting for Vault to be ready..."
               until curl -s http://{{ .Release.Name }}-vault:8200/v1/sys/health | grep -q '"initialized":false'; do
@@ -86,4 +98,3 @@ roleRef:
 subjects:
   - kind: ServiceAccount
     name: {{ .Release.Name }}-vault-init-sa
-{{- end }}
